<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/modules.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Back end modules
 */
 $GLOBALS['TL_LANG']['MOD']['iao']  = 'Project-Management';
 $GLOBALS['TL_LANG']['MOD']['iao_projects']	= array('Projects', 'Manage your projects here.');
 $GLOBALS['TL_LANG']['MOD']['iao_offer']	= array('all offers', 'Manage your offers here.');
 $GLOBALS['TL_LANG']['MOD']['iao_invoice']	= array('all invoices', 'Manage your invoices here.');
 $GLOBALS['TL_LANG']['MOD']['iao_reminder']	= array('all arrears', 'Manage your arrears here.');
 $GLOBALS['TL_LANG']['MOD']['iao_credit']	= array('all credit vouchers', 'Manage your credit vouchers here.');
 $GLOBALS['TL_LANG']['MOD']['iao_agreements']	= array('Agreements', 'Manage your service agreements and all chronological recurring invoice settings here.');
 $GLOBALS['TL_LANG']['MOD']['iao_templates']	= array('Templates (Text)', 'Manage templates for the default text before and after items of invoices, offers and credit vouchers.');
 $GLOBALS['TL_LANG']['MOD']['iao_templates_items']	= array('Templates (Items)', 'Manage templates for items of invoices, offers and credit vouchers.');
 $GLOBALS['TL_LANG']['MOD']['iao_customer']	= array('Customers', 'Manage your customers here.');
 $GLOBALS['TL_LANG']['MOD']['iao_settings']	= array('Settings', 'Manage your common settings for offers, invoices and credit vouchers.');
 $GLOBALS['TL_LANG']['MOD']['iao_setup']	= array('Setup', 'Manage all setups here.');

/**
 * settings Modules
 */
$GLOBALS['TL_LANG']['PMB']['config_module']             = 'Configuration for project management (Version: %s)';

$GLOBALS['TL_LANG']['PMB']['config']                       = 'Configuration';
$GLOBALS['TL_LANG']['PMB']['iao_settings'][0]              = 'Configurations';
$GLOBALS['TL_LANG']['PMB']['iao_settings'][1]              = 'Manage and assign the default configuration. You can add multiple configurations to manage various PDF templates for offers, invoices and more for different companies.';
$GLOBALS['TL_LANG']['PMB']['iao_tax_rates'][0]             = 'Tax rates';
$GLOBALS['TL_LANG']['PMB']['iao_tax_rates'][1]             = 'Tax rates are defining additional fees which should be added to the price.';
$GLOBALS['TL_LANG']['PMB']['iao_item_units'][0]            = 'Units';
$GLOBALS['TL_LANG']['PMB']['iao_item_units'][1]            = 'Manage units for items (As example hours, days, flat charge).';

$GLOBALS['TL_LANG']['PMB']['templates']                    = 'Templates';
$GLOBALS['TL_LANG']['PMB']['iao_templates'][0]             = 'Templates (Invoices, Offers, Credit vouchers)';
$GLOBALS['TL_LANG']['PMB']['iao_templates'][1]             = 'To fill out reccuring texts within invoices, offers or credit vouchers faster here you can manage them as templates.';
$GLOBALS['TL_LANG']['PMB']['iao_templates_items'][0]       = 'Item templates (Invoices, Offers, Credit vouchers)';
$GLOBALS['TL_LANG']['PMB']['iao_templates_items'][1]       = 'Here you create templates for the items of a invoice, offer or credit voucher.';


/**
 * Front end modules
 */
$GLOBALS['TL_LANG']['FMD']['iao_fe']      = 'Offers &amp; Invoices';
$GLOBALS['TL_LANG']['FMD']['fe_iao_invoice'] = array('List of invoices', 'A list of all invoices for the logged in member.');
$GLOBALS['TL_LANG']['FMD']['fe_iao_offer'] = array('List of offers','A list of all offers for the logged in member.');
$GLOBALS['TL_LANG']['FMD']['fe_iao_credit'] = array('List of credit vouchers','A list of all credit vouchers for the logged in member.');
$GLOBALS['TL_LANG']['FMD']['fe_iao_reminder'] = array('List of reminders','A list of all reminders for the logged in member.');
$GLOBALS['TL_LANG']['FMD']['fe_iao_agreements'] = array('List of all agreements','A list of all agreements for the logged in member.');
$GLOBALS['TL_LANG']['FMD']['fe_iao_public_project_list'] = array('Public project list','A list of all public accessable projects.');
