<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_templates_items.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao_templates_items']['title'] = array('Title','Title for this template');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['text'] = array('Template-Text','');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['position'] = array('Position','');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['headline'] = array('Headline','Item title');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['headline_to_pdf'] = array('Add headline to PDF','Should the headline be added within the PDF file before the text?');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['text'] = array('Description','Add a description for this item.');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['price'] = array('Price','Please enter an price.');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['vat_incl'] = array('Price with or without VAT','(gross / net)');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['count'] = array('Quantity','The quantity will be multiplicated with the price');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['amountStr'] = array('Type of quantity','');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['operator'] = array('Type for payment','Should this item be added or substraced?');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['vat'] = array('VAT','The type of VAT for this item.');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['published'] = array('published');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['new'] = array('New item template','Add a new item template');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['edit'] = array('Edit item template','Edit item template ID %s');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['copy'] = array('Duplicate item template','Duplicate item template ID %s');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['delete'] = array('Delete item template','Delete item template ID %s');

$GLOBALS['TL_LANG']['tl_iao_templates_items']['title_legend'] = 'Default settings';
$GLOBALS['TL_LANG']['tl_iao_templates_items']['item_legend'] = 'Item data';
$GLOBALS['TL_LANG']['tl_iao_templates_items']['publish_legend'] = 'Publishing';

$GLOBALS['TL_LANG']['tl_iao_templates_items']['vat_incl_percents'] = array(1 => 'net', 2 => 'gross');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['operators'] = array('+' => '+ (total)', '-' => '- (substract)');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['type_options'] = array('item'=>'Item','devider'=>'PDF Divider');
$GLOBALS['TL_LANG']['tl_iao_templates_items']['position_options'] = array('offer'=>'Offer', 'credit'=>'Credit voucher', 'invoice'=>'Invoice');
