<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_tax_rates.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['name'][0]              = 'Name of tax rate';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['name'][1]              = 'Please enter an unique name.';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['value'][0]				= 'Value (%)';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['value'][1]             = 'ie. 19 or 7 or 0';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['sorting'][0]				= 'Sorting';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['sorting'][1]             = 'To adjusted the sorting enter a number here.';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['default_value'] = array('Default value','This value will be used as predefined value on creating a new entry.');

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['new'][0]                          = 'New tax rate';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['new'][1]                          = 'Add a new tax rate.';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['edit'][0]                         = 'Edit tax rate';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['edit'][1]                         = 'Edit tax rate ID %s.';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['copy'][0]                         = 'Duplicate tax rate';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['copy'][1]                         = 'Duplicate tax rate ID %s.';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['delete'][0]                       = 'Delete tax rate';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['delete'][1]                       = 'Delete tax rate ID %s.';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['show'][0]                         = 'Show details of tax rate';
$GLOBALS['TL_LANG']['tl_iao_tax_rates']['show'][1]                         = 'Show details of tax rate ID %s.';

