<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_credit_items.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao_credit_items']['posten_template'] =	array('Template','Items-Template');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['headline'] =	array('Title','Item title');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['headline_to_pdf'] = ['Add title into PDF'];
$GLOBALS['TL_LANG']['tl_iao_credit_items']['type'] =	array('Content type','New entry or PDF page break');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['alias'] =	array('Alias','');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['author'] =	array('Item autor','');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['text'] =	array('Description','Enter an description for the item.');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['price'] =	array('Price','Enter an price.');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['vat_incl'] =	array('Price with or without VAT','(gross / net)');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['count'] =	array('Amount','The amount will be multiplicated with the price.');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['amountStr'] =	array('Type of amount','');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['vat'] =	array('VAT','Type of VAT for this item.');

/**
 * Global operation
 */
$GLOBALS['TL_LANG']['tl_iao_credit_items']['pdf'] =	array('Generate PDF','Generate a PDF for this credit voucher');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['new'] =	array('New item','Add a new item');

/**
 * Operation
 */
$GLOBALS['TL_LANG']['tl_iao_credit_items']['edit'] =	array('Edit item','Edit item ID %s');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['copy'] =	array('Duplicate item','Duplicate item ID %s');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['delete'] =	array('Delete item','Delete item ID %s');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['deleteConfirm'] = 'Do you really want to delete the itemn ID %s?!';
$GLOBALS['TL_LANG']['tl_iao_credit_items']['show'] =	array('Show details','Show details of item ID %s');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['postentemplate'] =	array('Save this item as template','Save itemn ID %s as template');

$GLOBALS['TL_LANG']['tl_iao_credit_items']['tstamp'] =	array('Last change','');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['published'] =	array('published','');

$GLOBALS['TL_LANG']['tl_iao_credit_items']['templates_legend'] = 'Template selection';
$GLOBALS['TL_LANG']['tl_iao_credit_items']['title_legend'] = 'Common settings';
$GLOBALS['TL_LANG']['tl_iao_credit_items']['item_legend'] = 'Item data';
$GLOBALS['TL_LANG']['tl_iao_credit_items']['publish_legend'] = 'Publishing';
$GLOBALS['TL_LANG']['tl_iao_credit_items']['type_legend'] = 'Element type settings';

$GLOBALS['TL_LANG']['tl_iao_credit_items']['vat_incl_percents'] =	array(1 => 'net', 2 => 'gross');
$GLOBALS['TL_LANG']['tl_iao_credit_items']['type_options'] =	array('item'=>'Item','devider'=>'PDF-Break');
