<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_template.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao_templates']['title'] = array('Title','Title for the template');
$GLOBALS['TL_LANG']['tl_iao_templates']['text'] = array('Template text','');
$GLOBALS['TL_LANG']['tl_iao_templates']['position'] = array('Position','');
$GLOBALS['TL_LANG']['tl_iao_templates']['new'] = array('New template','Add a new template');
$GLOBALS['TL_LANG']['tl_iao_templates']['edit'] = array('Edit template','Edit template ID %s');
$GLOBALS['TL_LANG']['tl_iao_templates']['copy'] = array('Duplicate templaten','Duplicate template ID %s');
$GLOBALS['TL_LANG']['tl_iao_templates']['delete'] = array('Delete template','Delete template ID %s');

$GLOBALS['TL_LANG']['tl_iao_templates']['template_options'] = array(
    'invoice_before_text'=>'Invoice text before items',
    'invoice_after_text'=>'Invoice text after items',
    'offer_before_text'=>'Offer text before items',
    'offer_after_text'=>'Offer text after items',
    'credit_before_text'=>'Credit voucher text before items',
    'credit_after_text'=>'Credit voucher text after items',
    );
