<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_projects.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

$GLOBALS['TL_LANG']['tl_iao_projects']['setting_id']	=	array('Configuration','');
$GLOBALS['TL_LANG']['tl_iao_projects']['title']	=	array('Title','Title of the element');
$GLOBALS['TL_LANG']['tl_iao_projects']['member']	=	array('Customer','Add address of saved customer into the following field');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_title']	=	array('Title for references','');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_customer']	=	array('Customer description','');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_todo']	=	array('Tasks','');
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_desription']	=	array('Project description','');
$GLOBALS['TL_LANG']['tl_iao_projects']['in_reference']	=	array('add to reference.','');
$GLOBALS['TL_LANG']['tl_iao_projects']['finished']	=	array('finished','');
$GLOBALS['TL_LANG']['tl_iao_projects']['singleSRC']	=	array('Project image','Will be used for all project teasers as main image');
$GLOBALS['TL_LANG']['tl_iao_projects']['multiSRC']	=	array('Project gallery','');
$GLOBALS['TL_LANG']['tl_iao_projects']['url']	=	array('www','Website-URL');
$GLOBALS['TL_LANG']['tl_iao_projects']['notice']	=	array('Notice','The notice will be used in backend only.');

/**
 * Buttons
 */
$GLOBALS['TL_LANG']['tl_iao_projects']['offer']	=	array('Project offers','All offers for this project');
$GLOBALS['TL_LANG']['tl_iao_projects']['invoice']	=	array('Project invoices','All invoices for this project');
$GLOBALS['TL_LANG']['tl_iao_projects']['credit']	=	array('Project credit vouchers','All credit vouchers for this project');
$GLOBALS['TL_LANG']['tl_iao_projects']['reminder']	=	array('Project reminders','All reminders for this project');
$GLOBALS['TL_LANG']['tl_iao_projects']['agreements']	=	array('Project agreements','All agreements for this project');
$GLOBALS['TL_LANG']['tl_iao_projects']['new']	=	array('Add new project','Add a new project');
$GLOBALS['TL_LANG']['tl_iao_projects']['edit']	=	array('Edit project','Edit project ID %s');
$GLOBALS['TL_LANG']['tl_iao_projects']['copy']	=	array('Duplicate project','Duplicate project ID %s');
$GLOBALS['TL_LANG']['tl_iao_projects']['delete']	=	array('Delete project','Delete project ID %s');
$GLOBALS['TL_LANG']['tl_iao_projects']['deleteConfirm']	=	'Do you really want to delete the project ID %s?!';
$GLOBALS['TL_LANG']['tl_iao_projects']['show']	=	array('Show details','Show details of project ID %s');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_iao_projects']['settings_legend']	=	'Configuration assignment';
$GLOBALS['TL_LANG']['tl_iao_projects']['project_legend']	=	'Project settings';
$GLOBALS['TL_LANG']['tl_iao_projects']['reference_legend']	=	'Reference assignment';

/**
* Frontend-Templates
*/
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['title'] = 'Title / Invoice number:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['date'] = 'created on:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['price'] = 'Amount:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['remaining'] = 'Open:';
$GLOBALS['TL_LANG']['tl_iao_projects']['fe_table_head']['file'] = 'PDF:';


// Meldungen
$GLOBALS['TL_LANG']['tl_iao_projects']['no_entries_msg'] = 'There are no entries for this type available.';
