<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_iao_agreements.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */


$GLOBALS['TL_LANG']['tl_iao_agreements']['setting_id']	=	array('Configuration','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['pid']	=	array('Project','Optionally you can select your project.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['title'] = array('Title','Title of the element.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['agreement_pdf_file'] = array('Agreement','Assign agreement as PDF file.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['member'] = array('Customer','Fill in address from saved customer into the following field.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['text_generate'] = array('Generate address text from customer data','ATTENTION! The exisiting address data may be deleted.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['address_text'] = array('Reminder address','Address which is written into the reminder PDF file.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['published'] = array('published','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['status'] = array('Status of this agreement','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['periode'] = array('Period','Enter the period with a strototime format. As example: +1 year = 1 Year forward, +2 months = other 2 months');
$GLOBALS['TL_LANG']['tl_iao_agreements']['agreement_date'] = array('Afreement since','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['beginn_date'] = array('Begin of cycle','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['end_date'] = array('End of cycle','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['terminated_date'] = array('terminate at','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['new_generate'] = array('Set the new cycle','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['sendEmail'] = array('Set up Email-reminder','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['remind_before'] = array('Remind before end of agreement cycle','The value must be as strtotime format (ie. -3 weeks).');
$GLOBALS['TL_LANG']['tl_iao_agreements']['email_from'] = array('Email sender','The email address of sender should be within same domain, otherwise maybe the server won\'t send the email.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['email_to'] = array('Email recipient','The email address to which a reminder should be sent, before thre agrrement cycle ends.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['email_subject'] = array('Email subject','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['email_text'] = array('Email text','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['before_template'] = array('Text before items','A selection of invoice items');
$GLOBALS['TL_LANG']['tl_iao_agreements']['after_template'] = array('Text after items','A selection of invoice items');
$GLOBALS['TL_LANG']['tl_iao_agreements']['posten_template'] = array('Item templates','A selection of invoice items');
$GLOBALS['TL_LANG']['tl_iao_agreements']['notice'] = array('Notice','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['price'] = array('Price','Enter an price.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['vat_incl'] = array('Price with or without tax?','(gross / net)');
$GLOBALS['TL_LANG']['tl_iao_agreements']['count'] = array('Amount','The amount will be multiplied with the price.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['amountStr'] = array('Type of the amount','');
$GLOBALS['TL_LANG']['tl_iao_agreements']['vat'] = array('VAT','Type of VAT for this item.');

$GLOBALS['TL_LANG']['tl_iao_agreements']['execute_date'] = array('Executed at','This value is mandatory by the finance office to get the input VAT.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['expiry_date'] = array('Payable till','The date from which the reminder steps are starting.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['invoice_pdf_file'] = array('Reminder file','If a file is selected, the file will be output instead of the generated. Under normal circumstances this field should be empty, it is primary used for imports only.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['paid_on_date'] = array('Paid at','The date the payment has been received at bank account.');
$GLOBALS['TL_LANG']['tl_iao_agreements']['invoice'] = array('Generate the service agreement for the current invoice.','Generate service agreement ID %s as invoice');
$GLOBALS['TL_LANG']['tl_iao_agreements']['toggle'] = 'Mark agreement as active / inactive';

/**
* Buttons
*/
$GLOBALS['TL_LANG']['tl_iao_agreements']['new'] = array('New Agreement','Add a new agreement');
$GLOBALS['TL_LANG']['tl_iao_agreements']['edit'] = array('Edit agreement','Edit agrrement ID %s');
$GLOBALS['TL_LANG']['tl_iao_agreements']['copy'] = array('Duplicate agreement','Duplicate agreement ID %s');
$GLOBALS['TL_LANG']['tl_iao_agreements']['delete'] = array('Delete agreement','Delete agreement ID %s');
$GLOBALS['TL_LANG']['tl_iao_agreements']['deleteConfirm'] = 'Do you really want to delete agreement ID %s ?!';
$GLOBALS['TL_LANG']['tl_iao_agreements']['show'] = array('Show details','Show details for agreement ID %s');

/**
 * Legend
 */
$GLOBALS['TL_LANG']['tl_iao_agreements']['invoice_generate_legend']	=	'Settings for generating an invoice';
$GLOBALS['TL_LANG']['tl_iao_agreements']['agreement_legend']	=	'Agreement settings';
$GLOBALS['TL_LANG']['tl_iao_agreements']['settings_legend']	=	'Configuration assignment';
$GLOBALS['TL_LANG']['tl_iao_agreements']['title_legend'] = 'Title settings';
$GLOBALS['TL_LANG']['tl_iao_agreements']['address_legend'] = 'Address data';
$GLOBALS['TL_LANG']['tl_iao_agreements']['status_legend'] = 'Status settings';
$GLOBALS['TL_LANG']['tl_iao_agreements']['email_legend'] = 'Email settings';
$GLOBALS['TL_LANG']['tl_iao_agreements']['other_legend'] = 'More settings';
$GLOBALS['TL_LANG']['tl_iao_agreements']['notice_legend'] = 'Add a note';

/**
 * Select-fiels options
 */
$GLOBALS['TL_LANG']['tl_iao_agreements']['status_options'] = array('1'=>'active','2'=>'terminated');
$GLOBALS['TL_LANG']['tl_iao_agreements']['vat_incl_percents'] = array(1 => 'net', 2 => 'gross');

/**
* Frontend-Templates
*/
$GLOBALS['TL_LANG']['tl_iao_agreements']['fe_table_head']['title'] = 'Title:';
$GLOBALS['TL_LANG']['tl_iao_agreements']['fe_table_head']['beginn_date'] = 'Begin of cycle:';
$GLOBALS['TL_LANG']['tl_iao_agreements']['fe_table_head']['end_date'] = 'End of cycle:';
$GLOBALS['TL_LANG']['tl_iao_agreements']['fe_table_head']['price'] = 'Amount:';
$GLOBALS['TL_LANG']['tl_iao_agreements']['fe_table_head']['file'] = 'Agreement (pdf):';


// Meldungen
$GLOBALS['TL_LANG']['tl_iao_agreements']['no_entries_msg'] = 'There are no entries for this type available.';

