<?php
/**
 * TL_ROOT/vendor/srhinow/project-manager-bundle/languages/de/tl_member.php
 *
 * Contao extension: project-manager-bundle
 * Deutsch translation file
 *
 * Copyright : &copy; Sven Rhinow <sven@sr-tag.de>
 * License   : LGPL
 * Author    : Sven Rhinow, http://www.sr-tag.de/
 * Translator: Sven Rhinow (scuM666)
 *
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish
 * permanent text corrections which are update-safe.
 */

/**
 * Fields
 */
$GLOBALS['TL_LANG']['tl_member']['myid'] = array('Customer ID','In case of imported data records, the records must have a connection to invoices, offers or credit vouchers of the customer record.');

/**
 * Legends
 */
$GLOBALS['TL_LANG']['tl_member']['import_settings'] = 'Import settings';
$GLOBALS['TL_LANG']['tl_member']['new']    = array('New customer', 'Add a new customer');
$GLOBALS['TL_LANG']['tl_member']['title']    = array('Academic title', 'ie. Dr. or Prof.');
$GLOBALS['TL_LANG']['tl_member']['text_generate'] = array('Generate address text from customer data','ATTENTION! The exisiting address data may be deleted.');
$GLOBALS['TL_LANG']['tl_member']['address_text'] = array('Address data','Address which will be written into the PDF file.');

$GLOBALS['TL_LANG']['tl_member']['custom_addresstext_legend'] = 'Adjusted address text';
